# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: '.'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
            - name: Google Apps Script (GAS) Action
  # You may pin to the exact commit or the version.
  # uses: shiftavenue/gas-action@2f22d5b94e3bb8b348336e8e5bae0f1d8f1076c9
  uses: shiftavenue/gas-action@v0.1.2
  with:
    # Specifies the operation that should be performed (e.g. push code, deploy or run script). Currently allowed values are: push, deploy, run
    command: 
    # OAuth2 access token associated with the Google Cloud account/user used for this action
    access-token: 
    # Apps Script project ID in which the script is located
    project-id: 
    # Directory that contains the script code
    script-dir: # optional, default is ./
    # Entrypoint function of the Apps Script script used when triggering an execution
    function: # optional, default is 
